set serveroutput on size 100000
spool 01_create_user.log

WHENEVER SQLERROR EXIT FAILURE ROLLBACK
WHENEVER OSERROR EXIT FAILURE ROLLBACK

CREATE USER "&&SCHEMA_NAME" identified by "&&SCHEMA_PASSWORD" profile default default tablespace "&&TABLESPACE" account unlock;
ALTER USER "&&SCHEMA_NAME" QUOTA UNLIMITED ON "&&TABLESPACE";
GRANT ADMINISTER SQL TUNING SET TO "&&SCHEMA_NAME";
GRANT ADVISOR TO "&&SCHEMA_NAME";
GRANT ANALYZE ANY TO "&&SCHEMA_NAME";
GRANT aq_administrator_role TO "&&SCHEMA_NAME";
GRANT CONNECT to "&&SCHEMA_NAME";
GRANT CREATE ANY JOB TO "&&SCHEMA_NAME";
GRANT CREATE ANY PROCEDURE TO "&&SCHEMA_NAME";
GRANT CREATE ANY SYNONYM TO "&&SCHEMA_NAME";
GRANT CREATE ANY TABLE TO "&&SCHEMA_NAME";
GRANT CREATE ANY TRIGGER TO "&&SCHEMA_NAME";
GRANT CREATE DATABASE LINK TO "&&SCHEMA_NAME";
GRANT CREATE EXTERNAL JOB TO "&&SCHEMA_NAME";
GRANT CREATE JOB TO "&&SCHEMA_NAME";
GRANT CREATE MATERIALIZED VIEW TO "&&SCHEMA_NAME";
GRANT CREATE SEQUENCE TO "&&SCHEMA_NAME";
GRANT CREATE TABLE TO "&&SCHEMA_NAME";
GRANT CREATE TRIGGER TO "&&SCHEMA_NAME";
GRANT CREATE VIEW TO "&&SCHEMA_NAME";
GRANT DBA to "&&SCHEMA_NAME";
GRANT DEBUG ANY PROCEDURE TO "&&SCHEMA_NAME";
GRANT DEBUG CONNECT SESSION TO "&&SCHEMA_NAME";
GRANT DROP ANY TABLE TO "&&SCHEMA_NAME";
GRANT DROP ANY TRIGGER TO "&&SCHEMA_NAME";
GRANT EXECUTE ANY CLASS TO "&&SCHEMA_NAME";
GRANT EXECUTE ANY PROCEDURE TO "&&SCHEMA_NAME";
GRANT EXECUTE ANY PROGRAM TO "&&SCHEMA_NAME";
GRANT EXECUTE ON dbms_aq TO "&&SCHEMA_NAME";
GRANT EXECUTE ON dbms_aqadm TO "&&SCHEMA_NAME";
GRANT EXECUTE on SYS.DBMS_LOCK to "&&SCHEMA_NAME";
GRANT EXECUTE on SYS.DBMS_WORKLOAD_REPOSITORY to "&&SCHEMA_NAME";
GRANT MANAGE SCHEDULER TO "&&SCHEMA_NAME";
GRANT OEM_ADVISOR to "&&SCHEMA_NAME";
GRANT RESOURCE to "&&SCHEMA_NAME";
GRANT SELECT ANY DICTIONARY TO "&&SCHEMA_NAME";

WHENEVER SQLERROR CONTINUE

spool off