/*
Before execution, please replace variables started with ":" sign.
Script creates user with numerous grants.
*/
CREATE USER "ASZ_TEST_USER" identified by ":your_password" profile default default tablespace ":your_tablespace" account unlock;
ALTER USER "ASZ_TEST_USER" QUOTA UNLIMITED ON ":your_tablespace";
GRANT ADMINISTER SQL TUNING SET TO "ASZ_TEST_USER";
GRANT ADVISOR TO "ASZ_TEST_USER";
GRANT ANALYZE ANY TO "ASZ_TEST_USER";
GRANT aq_administrator_role TO "ASZ_TEST_USER";
GRANT CONNECT to "ASZ_TEST_USER";
GRANT CREATE ANY JOB TO "ASZ_TEST_USER";
GRANT CREATE ANY PROCEDURE TO "ASZ_TEST_USER";
GRANT CREATE ANY SYNONYM TO "ASZ_TEST_USER";
GRANT CREATE ANY TABLE TO "ASZ_TEST_USER";
GRANT CREATE ANY TRIGGER TO "ASZ_TEST_USER";
GRANT CREATE DATABASE LINK TO "ASZ_TEST_USER";
GRANT CREATE EXTERNAL JOB TO "ASZ_TEST_USER";
GRANT CREATE JOB TO "ASZ_TEST_USER";
GRANT CREATE MATERIALIZED VIEW TO "ASZ_TEST_USER";
GRANT CREATE SEQUENCE TO "ASZ_TEST_USER";
GRANT CREATE TABLE TO "ASZ_TEST_USER";
GRANT CREATE TRIGGER TO "ASZ_TEST_USER";
GRANT CREATE VIEW TO "ASZ_TEST_USER";
GRANT DBA to "ASZ_TEST_USER";
GRANT DEBUG ANY PROCEDURE TO "ASZ_TEST_USER";
GRANT DEBUG CONNECT SESSION TO "ASZ_TEST_USER";
GRANT DROP ANY TABLE TO "ASZ_TEST_USER";
GRANT DROP ANY TRIGGER TO "ASZ_TEST_USER";
GRANT EXECUTE ANY CLASS TO "ASZ_TEST_USER";
GRANT EXECUTE ANY PROCEDURE TO "ASZ_TEST_USER";
GRANT EXECUTE ANY PROGRAM TO "ASZ_TEST_USER";
GRANT EXECUTE ON dbms_aq TO "ASZ_TEST_USER";
GRANT EXECUTE ON dbms_aqadm TO "ASZ_TEST_USER";
GRANT EXECUTE on SYS.DBMS_LOCK to "ASZ_TEST_USER";
GRANT EXECUTE on SYS.DBMS_WORKLOAD_REPOSITORY to "ASZ_TEST_USER";
GRANT MANAGE SCHEDULER TO "ASZ_TEST_USER";
GRANT OEM_ADVISOR to "ASZ_TEST_USER";
GRANT RESOURCE to "ASZ_TEST_USER";
GRANT SELECT ANY DICTIONARY TO "ASZ_TEST_USER";